# .scrutinizer.yml
filter:
    paths: [src/*]
tools:
    php_code_coverage: true
    external_code_coverage: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
