language: php

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.2
      env: SYMFONY_VERSION='3.0.*'
    - php: 7.2
      env: SCRUTINIZER_REPORT=true
      env: SYMFONY_VERSION='4.0.*'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phing build
  - bin/permcheck -c permcheck.example.xml

after_script: >
  [ "$SCRUTINIZER_REPORT" = true ]
  && wget https://scrutinizer-ci.com/ocular.phar
  && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
